In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
b=np.array([5,6,7])
b

array([5, 6, 7])

In [4]:
c=np.array([0,4,5,6])
c

array([0, 4, 5, 6])

In [5]:
f=np.eye(4)
print("Array identify f\n:",f)

Array identify f
: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
f=np.eye(20)
print("array identifly f\n:",f)

array identifly f
: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

In [7]:
f=np.eye(24)
print("array identifly f\n",f)

array identifly f
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0

In [9]:
f=np.eye(12)
print("array identifly f\n:",f)

array identifly f
: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [10]:
f=np.eye(4)
print("array identifly f\n:",f)

array identifly f
: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
f=np.eye(-3)
print("array identifly f\n:",f)

ValueError: negative dimensions are not allowed

In [12]:
f=np.eye(3)
print("array identifly f\n:",f)

array identifly f
: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
f=np.eye(5)
print("array identifly f\n:",f)

array identifly f
: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
#Array Manuplation Function

In [16]:
a=np.array ([1,2,3,4])
reshaped=np.reshape(a,(4,1))
print("Reshaped array:",resheped)

NameError: name 'resheped' is not defined

In [17]:
import numpy as np

a = np.array([1, 2, 3, 4])

reshaped = np.reshape(a, (4, 1))

print("Reshaped array:", reshaped)

Reshaped array: [[1]
 [2]
 [3]
 [4]]


In [22]:
a = np.array([5,6,7,8])
reshaped=np.reshape(a,(4,1))
print('reshaped array:',reshaped)

reshaped array: [[5]
 [6]
 [7]
 [8]]


In [19]:


a = np.array([5, 6, 7, 8])

reshaped = np.reshape(a, (4, 1))

print('Reshaped array:', reshaped)

Reshaped array: [[5]
 [6]
 [7]
 [8]]


In [23]:
a = np.array([5,6,7])
reshaped=np.reshape(a,(3,1))
print('reshaped array:',reshaped)

reshaped array: [[5]
 [6]
 [7]]


In [24]:
a = np.array([5,6,7,8,9,0,1])
reshaped=np.reshape(a,(7,1))
print('reshaped array:',reshaped)

reshaped array: [[5]
 [6]
 [7]
 [8]
 [9]
 [0]
 [1]]


In [25]:
a = np.array([5,6,7,2,3,4,5,8])
reshaped=np.reshape(a,(8,1))
print('reshaped array:',reshaped)

reshaped array: [[5]
 [6]
 [7]
 [2]
 [3]
 [4]
 [5]
 [8]]


In [26]:
a = np.array([5,6,7,8,6,6])
reshaped=np.reshape(a,(6,1))
print('reshaped array:',reshaped)

reshaped array: [[5]
 [6]
 [7]
 [8]
 [6]
 [6]]


In [28]:
f1=np.array([[1,2],[3,4],[5,6],[7,8]])
flattened=np.ravel(f1)
print("flattened array:",flattened)

flattened array: [1 2 3 4 5 6 7 8]


In [30]:
f2=np.array([[1,3],[4,5],[7,8]])
flattened=np.ravel(f2)
print("flattened array:",flattened)

flattened array: [1 3 4 5 7 8]


In [31]:
f3=np.array([[5,6],[2,4],[5,6]])
flattened=np.ravel(f3)
print("flattened array:",flattened)

flattened array: [5 6 2 4 5 6]


In [33]:
f4=np.array([[3,45],[5,6],[7,8]])
flattened=np.ravel(f4)
print("flattened:",flattened)

flattened: [ 3 45  5  6  7  8]


In [34]:
f4=np.array([[3,45],[5,6],[7,8]])
transposed=np.transpose(f4)
print("transposed array:",transposed)

transposed array: [[ 3  5  7]
 [45  6  8]]


In [35]:
f4=np.array([[3,45],[5,8],[7,9]])
transposed=np.transpose(f4)
print("transposed array:",transposed)

transposed array: [[ 3  5  7]
 [45  8  9]]


In [36]:
f4=np.array([[13,55],[5,16],[7,18]])
transposed=np.transpose(f4)
print("transposed array:",transposed)

transposed array: [[13  5  7]
 [55 16 18]]


In [37]:
f4=np.array([[33,45],[55,6],[77,8]])
transposed=np.transpose(f4)
print("transposed array:",transposed)

transposed array: [[33 55 77]
 [45  6  8]]


In [38]:
f4=np.array([[90,45],[90,6],[90,8]])
transposed=np.transpose(f4)
print("transposed array:",transposed)

transposed array: [[90 90 90]
 [45  6  8]]


In [40]:
f4=np.array([[3,45],[5,6],[7,8]])
transposed=np.transpose(f4)
print("transposed array:",transposed)

transposed array: [[ 3  5  7]
 [45  6  8]]


In [ ]:
f4=np.array([[3,45],[5,6],[7,8]])
transposed=np.transpose(f4)
print("transposed array:",transposed)

In [1]:
#indexing

In [3]:
import numpy as np

In [4]:
t=np.arange(0,100).reshape(10,10)
t

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [5]:
row=4
col=5

In [6]:
col

5

In [7]:
row

4

In [8]:
t

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [9]:
t(row,col)

TypeError: 'numpy.ndarray' object is not callable

In [10]:
t

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [11]:
t[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [14]:
col=6
t

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [13]:
t

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [15]:
t[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [16]:
col=6
t[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [17]:
col=5
t[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [20]:
row=4
t[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [21]:
col=8
t[:,col]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [22]:
t

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [23]:
t[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [24]:
row=4
t[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [26]:
row=5
t[row,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [27]:
row=9
t[row,:]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])