In [ ]:
#numpy Crash Course

In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
import sys
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

In [ ]:
#Creating Arrays

In [4]:
my_list=[0,1,2,3,4,5,6,7,8,9]
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
type(my_list)

list

In [6]:
arr=np.array(my_list)

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(90)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [12]:
np.arange(90.0)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89.])

In [13]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np.arange(9,5)

array([], dtype=int64)

In [15]:
np.arange(90,100)

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
np.arange(90,900)

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
       103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
       116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
       129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
       142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
       155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
       168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180,
       181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193,
       194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206,
       207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219,
       220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232,
       233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245,
       246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258,
       259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 27

In [17]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [18]:
np.arange(-90,50)

array([-90, -89, -88, -87, -86, -85, -84, -83, -82, -81, -80, -79, -78,
       -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66, -65,
       -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53, -52,
       -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39,
       -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26,
       -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13,
       -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,
         1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49])

In [19]:
np.arange(12,4)

array([], dtype=int64)

In [20]:
np.arange(10,10)

array([], dtype=int64)

In [21]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(90)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [23]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
np.zeros((90,900))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(90, 900))

In [28]:
np.zeros((9090,9090))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(9090, 9090))

In [29]:
np.zeros((100,100))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(100, 100))

In [30]:
np.ones(90)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.])

In [31]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.ones((90,90))

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], shape=(90, 90))

In [33]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [34]:
n=6
n

6

In [35]:
np.ones(n)

array([1., 1., 1., 1., 1., 1.])

In [36]:
np.twos(7)

AttributeError: module 'numpy' has no attribute 'twos'

In [37]:
np.three(3)

AttributeError: module 'numpy' has no attribute 'three'

In [39]:
np.three(5,4)

AttributeError: module 'numpy' has no attribute 'three'

In [40]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [42]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [44]:
range(90)

range(0, 90)

In [45]:
range(9)

range(0, 9)

In [50]:
i=9
for i in range(9):
    print(i)

0
1
2
3
4
5
6
7
8


In [49]:
i=4
for i in range(4):
    print(i)

0
1
2
3


In [52]:
i=3
for i in range(3):
        print(i)

0
1
2


In [54]:
i=8
for i in range(8):
  print(i)

0
1
2
3
4
5
6
7


In [55]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [56]:
list(range(9,9))

[]

In [57]:
list(range(4,50))

[4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [58]:
np.rand(9)

AttributeError: module 'numpy' has no attribute 'rand'

In [59]:
np.random.rand(9,4)

array([[0.56426932, 0.75830532, 0.47262932, 0.24594897],
       [0.27360009, 0.70944404, 0.56668697, 0.49287609],
       [0.37966367, 0.42965437, 0.83948795, 0.21990445],
       [0.59325379, 0.93465302, 0.5615489 , 0.55497295],
       [0.15654307, 0.82839088, 0.94570063, 0.72426163],
       [0.27076119, 0.67338038, 0.75258395, 0.43578581],
       [0.2197872 , 0.21733577, 0.90169454, 0.93711056],
       [0.45866549, 0.65060889, 0.02461349, 0.73866419],
       [0.73326482, 0.54878155, 0.39023926, 0.94320396]])

In [60]:
np.random.rand(6,3)

array([[0.68647103, 0.47146124, 0.23793597],
       [0.25135739, 0.81564081, 0.42899195],
       [0.79801523, 0.89032133, 0.91206604],
       [0.64818834, 0.69350552, 0.61306622],
       [0.43507352, 0.25692308, 0.70210916],
       [0.18020517, 0.7225238 , 0.02123998]])

In [61]:
np.random.rand(3,2)

array([[0.59872767, 0.70510508],
       [0.26811793, 0.91369056],
       [0.67503794, 0.52797312]])

In [62]:
np.random.randint(9)

2

In [64]:
np.random.randint(99)

77

In [65]:
np.random.randint(99)

26

In [66]:
np.random.randint(7,12)

11

In [68]:
np.random.randint(10,50,10)

array([28, 32, 22, 40, 14, 33, 16, 23, 43, 35], dtype=int32)

In [69]:
np.random.randint(10,50,10)

array([14, 34, 45, 25, 31, 27, 43, 29, 12, 21], dtype=int32)

In [70]:
np.random.randint(10,50,10)

array([37, 13, 14, 21, 36, 27, 47, 32, 24, 39], dtype=int32)

In [71]:
np.random.randint(10,50,10)

array([49, 11, 49, 28, 13, 14, 47, 33, 21, 12], dtype=int32)

In [72]:
np.random.rand(9)

array([0.70411705, 0.23789173, 0.44325658, 0.2119114 , 0.04838578,
       0.12727106, 0.94487612, 0.13977123, 0.90089271])