In [1]:
import numpy as np

In [2]:
a=([1,2,3,4,5,6,7,8,9])
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
np.shape()

TypeError: shape() missing 1 required positional argument: 'a'

In [7]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.empty(6)

array([2.37663529e-312, 2.14321575e-312, 2.14321575e-312, 1.10343781e-312,
       9.34600962e-307, 1.11262266e-307])

In [12]:
np.linspace(1,4)

array([1.        , 1.06122449, 1.12244898, 1.18367347, 1.24489796,
       1.30612245, 1.36734694, 1.42857143, 1.48979592, 1.55102041,
       1.6122449 , 1.67346939, 1.73469388, 1.79591837, 1.85714286,
       1.91836735, 1.97959184, 2.04081633, 2.10204082, 2.16326531,
       2.2244898 , 2.28571429, 2.34693878, 2.40816327, 2.46938776,
       2.53061224, 2.59183673, 2.65306122, 2.71428571, 2.7755102 ,
       2.83673469, 2.89795918, 2.95918367, 3.02040816, 3.08163265,
       3.14285714, 3.20408163, 3.26530612, 3.32653061, 3.3877551 ,
       3.44897959, 3.51020408, 3.57142857, 3.63265306, 3.69387755,
       3.75510204, 3.81632653, 3.87755102, 3.93877551, 4.        ])

In [18]:
np.dtype

numpy.dtype

In [22]:
np.shape(4)

()

In [25]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a)

[1 2 3 4]


In [26]:
np.shape

<function shape at 0x00000204CEDDC070>

In [27]:
np.ndim

<function ndim at 0x00000204CEDDE1F0>

In [28]:
np.linspace

<function linspace at 0x00000204CEE186F0>

In [30]:
np.linspace(1,3)

array([1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
       1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694,
       1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
       1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ,
       1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
       2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347,
       2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
       2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673,
       2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
       2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ])

In [31]:
np.linspace(0,3)

array([0.        , 0.06122449, 0.12244898, 0.18367347, 0.24489796,
       0.30612245, 0.36734694, 0.42857143, 0.48979592, 0.55102041,
       0.6122449 , 0.67346939, 0.73469388, 0.79591837, 0.85714286,
       0.91836735, 0.97959184, 1.04081633, 1.10204082, 1.16326531,
       1.2244898 , 1.28571429, 1.34693878, 1.40816327, 1.46938776,
       1.53061224, 1.59183673, 1.65306122, 1.71428571, 1.7755102 ,
       1.83673469, 1.89795918, 1.95918367, 2.02040816, 2.08163265,
       2.14285714, 2.20408163, 2.26530612, 2.32653061, 2.3877551 ,
       2.44897959, 2.51020408, 2.57142857, 2.63265306, 2.69387755,
       2.75510204, 2.81632653, 2.87755102, 2.93877551, 3.        ])

In [32]:
g=np.array([1,2,3])
g

array([1, 2, 3])

In [33]:
type(g)

numpy.ndarray

In [34]:
g2=np.array((1,2,3))
g2

array([1, 2, 3])

In [37]:
type(g2)

numpy.ndarray

In [38]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [41]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [43]:
np.full(9,13)

array([13, 13, 13, 13, 13, 13, 13, 13, 13])

In [44]:
np.full(0,3)

array([], dtype=int64)

In [45]:
np.full(3,0)

array([0, 0, 0])

In [46]:
np.full(4,5)

array([5, 5, 5, 5])

In [47]:
np.full(90,9)

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9])

In [48]:
np.full(0,5)

array([], dtype=int64)

In [49]:
np.full(5,0)

array([0, 0, 0, 0, 0])

In [50]:
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [51]:
a[0]

np.int64(10)

In [52]:
a[1]

np.int64(20)

In [53]:
a[-1]

np.int64(50)

In [54]:
a[-2]

np.int64(40)

In [55]:
a[:0]

array([], dtype=int64)

In [56]:
a[::]

array([10, 20, 30, 40, 50])

In [57]:
a[::-2]

array([50, 30, 10])

In [58]:
a[::2]

array([10, 30, 50])

In [61]:
b=np.array([ [1,2,3,4],
             [9,10,11,12],
             [14,15,16,17],
             [21,22,23,24]])
b

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [14, 15, 16, 17],
       [21, 22, 23, 24]])

In [65]:
b[0:4]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [14, 15, 16, 17],
       [21, 22, 23, 24]])

In [66]:
b[0]

array([1, 2, 3, 4])

In [67]:
b[0:0]

array([], shape=(0, 4), dtype=int64)

In [68]:
b[1:3]

array([[ 9, 10, 11, 12],
       [14, 15, 16, 17]])

In [69]:
b[2:4]

array([[14, 15, 16, 17],
       [21, 22, 23, 24]])

In [70]:
b[0:2,1:3]

array([[ 2,  3],
       [10, 11]])